proxy:
    image: proxy:1.0
    links:
        - identidock
    ports:
        - "80:80"
    environment:
        - NGINX_HOST=localhost
        - NGINX_PROXY=http://identidock:9090
identidock:
    extends:
        file: common.yml
        service: identidock
    environment:
        ENV: PROD
dnmonster:
    extends:
        file: common.yml
        service: dnmonster    
redis:
    extends:
        file: common.yml
        service: redis
